config/routes.rb
Rails.application.routes.draw do










  get "/404", :to => "error#page_not_found"

  get "/bt_token", :to => "application#get_braintree_token"
  get "/terms", :to => "application#terms_of_service"
  get "/privacy", :to => "application#privacy_policy"

  root 'doge#index'

  post "/woof" => "doge#woof"
  get  "/doge_enqueue" => "doge#doge_timer"
  post "/doge_enqueue" => "doge#doge_enqueue"
  get  "/doge_control" => "doge#doge_control"
  post "/doge_control" => "doge#doge_control_signal"
  get  "/doge_token_dropin" => "doge#doge_token_dropin"
  post "/doge_token_dropin" => "doge#post_doge_token_dropin"

  resources :accounts, only: [:new, :create, :update, :show]
  get  "/login" => "accounts#login"
  post "/login" => "accounts#post_login"
  get  "/logout" => "accounts#logout"
  get  "/color" => "accounts#color"
  post "/color" => "accounts#change_color"

  get "/purchase" => "purchase#buy_token"
  post "/purchase" => "purchase#post_buy_token"

  get "/doge_purchase_test" => "doge#purchase"
end

app/views/layouts/_background.html.erb
<div class="app_background">
</div>

app/views/layouts/_footer.html.erb
<div id="dogeFooterContainer">
  <div id="dogeFooterContentContainer">
    <div id="dogeTermsOfService" class="dogeFooterLinkContainer">
      <%= link_to "Terms of Service", terms_path, method: :get, class: "dogeFooterLink" %>
    </div>
    <div id="dogePrivacyPolicy" class="dogeFooterLinkContainer">
      <%= link_to "Privacy Policy", privacy_path, method: :get , class: "dogeFooterLink" %>
    </div>
    <div id="dogeCertification" class="dogeFooterLinkContainer">
      <span id="cdSiteSeal1">
        <script type="text/javascript" src="//tracedseals.starfieldtech.com/siteseal/get?scriptId=cdSiteSeal1&amp;cdSealType=Seal1&amp;sealId=55e4ye7y7mb73e24b240e1b2ec14wv19juc14y7mb7355e4ye742c985b0447332">
        </script>
      </span>
    </div>
  </div>
</div>

app/views/layouts/_ls_form_container.html.erb
<div id="ls_form_container">
  <div id="backdrop"></div>
  <div id="center_form" class="hori-center">
    <div id="form_pop_up">
      <table id="form_tabs_table">
        <tr id="form_tabs_row">
          <td id="signup_tab" class="pointer">Sign Up<div id="signup_cover" class="cover"></div></td>
          <td class="space-cell" class="ctx">-</td>
          <td id="login_tab" class="pointer">Log In<div id="login_cover" class="cover"></div></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doge</title>
  <!-- 
    Gon gem allows us to add variables in the controller that javascript can access through the gon object
  
    Ex:
    class ProductsController < ApplicationController
      def index
        gon.products = Product.limit(10)
      end
    end 
  -->
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Roboto" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.braintreegateway.com/web/dropin/1.4.0/js/dropin.min.js" %>
  <%= javascript_include_tag "https://js.braintreegateway.com/web/3.20.0/js/data-collector.min.js" %>
  <%= javascript_include_tag "color-pick-bundle" %>
  <%= javascript_include_tag "color-opener-bundle" %>
  <%= csrf_meta_tags %>
</head>
<body id="dogeAppBody">

<!-- Header HTML -->
<div id="login_bar">
  <div id="logo_container">
    <%= link_to image_tag("dogetime.png", id: "logo"), root_path, method: :get, id: "logo-link", class: "vert-center" %>
  </div>
  <div id="title_container"><p id="doge_title" class="vert-center"></p></div>
  <table id="title_table" class="vert-center">
    <tr>
      <% if session[:logged_in] then %>
        <%= form_tag color_path, :method => "post", :remote => true, :id => "change_color_form" do%>
          <%= hidden_field_tag "account_color", session[:color] %>
        <% end %>
        <td class="color_picker_general">
          <canvas height="64px" width="64px" id="open_color_picker"></canvas>
          <div id="color_picker_location2"></div>
          <script type="text/javascript">
            var app_color_opener = new ColorOpener ("<%= session[:color] %>",
                                                    "open_color_picker",
                                                    "color_picker_location2",
                                                    "color-picker-container");
            app_color_opener.bindSubmission ("change_color_form");
          </script>
        </td>
        <td class="welcome">Welcome <%= link_to(sanitize(session[:username]), account_path(session[:id]), style: "color:" + sanitize(session[:color]), method: :get, id: "username_top") %>!</td>
        <td>|</td>
	      <td class="login_link"><%= link_to "Log Out", logout_path, remote: true, id: "logout_link" %></td>
	      <%= javascript_include_tag "logout-bundle" %>
      <% else %>
        <td class="login_link"><%= link_to "Sign up", new_account_path, remote: true, id: "signup_link" %></td>
        <td>|</td>
	      <td class="login_link"><%= link_to "Login", login_path, remote: true, id: "login_link" %></td>
        <%= javascript_include_tag "login-signup-bundle" %>
      <% end %>
      <%= hidden_field_tag "current_account_color", session[:color] %>
      <%= hidden_field_tag "current_account_username", session[:username] %>
    </tr>
  </table>
</div>

<%= yield %>

<%= render "layouts/footer" %>

<%= render "layouts/ls_form_container" %>

</body>
</html>