config/routes.rb
Rails.application.routes.draw do










  get "/404", :to => "error#page_not_found"

  get "/bt_token", :to => "application#get_braintree_token"
  get "/terms", :to => "application#terms_of_service"
  get "/privacy", :to => "application#privacy_policy"

  root 'doge#index'

  post "/woof" => "doge#woof"
  get  "/doge_enqueue" => "doge#doge_timer"
  post "/doge_enqueue" => "doge#doge_enqueue"
  get  "/doge_control" => "doge#doge_control"
  post "/doge_control" => "doge#doge_control_signal"
  get  "/doge_token_dropin" => "doge#doge_token_dropin"
  post "/doge_token_dropin" => "doge#post_doge_token_dropin"

  resources :accounts, only: [:new, :create, :update, :show]
  get  "/login" => "accounts#login"
  post "/login" => "accounts#post_login"
  get  "/logout" => "accounts#logout"
  get  "/color" => "accounts#color"
  post "/color" => "accounts#change_color"

  get "/purchase" => "purchase#buy_token"
  post "/purchase" => "purchase#post_buy_token"

  get "/doge_purchase_test" => "doge#purchase"
end

app/models/account.rb
class Account < ActiveRecord::Base

  has_one :queue_request, dependent: :destroy
  
  before_validation :clean_color
  validates :username, presence: true, length: { minimum: 3 }
  validate :color_valid
  validate :username_not_taken, :on => :create
  validate :password_check, :on => :create

  def clean_color
    self.color = ActionController::Base.helpers.sanitize (self.color); 
  end

  def username_not_taken
    if Account.find_by_username(username) != nil then
      errors.add(:username, "is already taken")
    end 
  end

  def password_check
    if not @password.present?
      errors.add(:password, "can't be blank")
    end
    if @password.length < 8
      errors.add(:password, "is too short (minimum is 8 characters)")
    end
  end

  def color_valid
    # color will always be valid. No check added yet
    if false then
      errors.add(:color, "Color is invalid.")
    end
  end

  def password_valid?(check_password)
    sha512 = OpenSSL::Digest.new('sha512')
    check_password_digest = OpenSSL::HMAC.hexdigest(sha512, Rails.application.secrets.doge_secret, check_password + self.salt)
    return password_digest == check_password_digest
  end

  def password=(set_password)
    @password = set_password
    self.salt = SecureRandom.hex(256)
    sha512 = OpenSSL::Digest.new('sha512')
    self.password_digest = OpenSSL::HMAC.hexdigest(sha512, Rails.application.secrets.doge_secret, set_password + self.salt)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    if @account == nil then
      @account = Account.new
    end
    if params.has_key?(:special_message)
      @account.errors.add(:base, params[:special_message])
      response.headers["signup-error"] = "true"
      render "new"
    end
    @color = session[:color]
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.password=(params[:account][:password])
    if @account.save then
      response.headers["signup-error"] = "false"
      session[:logged_in] = true
      session[:id] = @account.id
      session[:username] = @account.username
      session[:color] = @account.color
      head :ok
    else
      response.headers["signup-error"] = "true"
      render "new"
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /accounts/login
  def login 
  end

  # POST /accounts/post_login
  def post_login
    error = nil
    if params[:login][:username] == "" || params[:login][:password] == "" then
      error = "Enter a username and password"
    else
      @account = Account.find_by_username(params[:login][:username])
      if @account == nil then
	      error = "Invalid username or password"
      else
        if not @account.password_valid? params[:login][:password] then
	        error = "Invalid username or password"
	      end
      end
    end
    if error != nil then
      flash[:login_form] = true
      flash[:login_error] = error
    else
      session[:logged_in] = true
      session[:id] = @account.id
      session[:username] = @account.username
      session[:color] = @account.color
    end
    head :ok, :login_error => error != nil
  end

  # GET /accounts/logout
  def logout
    reset_session
    if request.xhr?
      head :ok
    else
      redirect_to controller: 'doge', action: 'index'
    end
  end

  # GET /color
  def color
    if session[:logged_in] then
      # TODO Put these in a gon variable some day
      @image = "color_picker_top.png"
      @container_class = "color_container_top"
      @image_class = "color_picker_img_top"
      @color_picker_class = "color_picker_div_top"
      @opener = "open_color_picker"
    else
      @image = "color_picker.png"
      @container_class = "color_container"
      @image_class = "color_picker_img"
      @color_picker_class = ["vert-center", "color_picker_div"]
      @opener = "open_color_picker_signup"
    end
  end

  # POST /color
  def change_color
    if session[:logged_in] then
      session[:color] = params[:account_color]
      @account = Account.find_by_username(session[:username])
      @account.color = session[:color]
      @account.save
    end
    response.headers["color"] = session[:color]
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :password, :color)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_color_picker.html.erb
<div id="color-picker-container" class=<%= @container_class %>>
  <%= image_tag @image, class: @image_class, usemap: "#color_picker_map" %>
  <!-- Image Map doesn't yet work -->
  <map name="Map" id="color_picker_map">
    <area shape="poly" coords="<%= @map_coords %>">
  </map>
  <%= content_tag "div", id: "color-picker-canvas", class: @color_picker_class do %>
    <canvas id="sv-canvas" class="color-picker" width="150px" height="180px"></canvas>
    <canvas id="h-canvas" class="color-picker" width="15px" height="180px"></canvas>
  <% end %>
  <script type="text/javascript">
  var signup_picker = new ColorPicker ("color-picker-container", "sv-canvas", "h-canvas",
                                       <%= @opener %>.id, "account_color");
  </script>  
</div>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_login_form.html.erb
<div id="login_form_container" class="form_container">
  <div id="login_box" class="form_box">
    <%= image_tag "exit_normal.png", id: "exit_button",
                   draggable: "false" %>
    <p id="login_title" class="form_title">So Login, Much Doge</p>
    <div id="login_info" class="form_info">
      <%= form_for :login, remote: true, html: {id: "login_form"} do |f| %>
        <div class="form_input_container">
          <%= f.label :username, id: "username_label", class: "form_label" %>
          <%= f.text_field :username, class: "form_input" %>
        </div>
        <div class="form_input_container">
          <%= f.label :password, id: "password_label", class: "form_label" %>
          <%= f.password_field :password, class: "form_input" %>
        </div>
        <% if flash[:login_error] %>
          <div id="login_error" class="error form_error"><%= sanitize flash[:login_error] %></div>
        <% end %>
        <div id="underline" class="underline"></div>
        <%= image_tag "doge_face_thumb.png", id: "login_form_doge_img", class: "hori-center form_img" %>
        <div id="login_submit_container" class="form_input_container">
          <%= f.submit "Login", class: "form_submit hori-center", id: "login_form_submit" %>
        </div>
      <% end %>
    </div>
  </div>
  <%= javascript_include_tag "exit-button-bundle" %>
  <%= javascript_include_tag "login-form-bundle" %>
  <script type="text/javascript">
    var exitButton = new makeExitButton ("exit_button", "login_form_container",
                                         "<%= asset_path('exit_normal.png') %>",
                                         "<%= asset_path('exit_highlight.png') %>",
                                         "<%= asset_path('exit_pressed.png') %>");
    exitButton.bindClick (function () {
      $("#ls_form_container").css ("display", "none");
    });
  </script>
  <div id="preload_login_form" class="form_preload">
    <%= image_tag "exit_highlight.png", height: "1px", width: "1px" %>
    <%= image_tag "exit_pressed.png", height: "1px", width: "1px" %>
  </div>
</div>

app/views/accounts/_sign_up_form.html.erb
<div id="signup_form_container" class="form_container">
  <div id="signup_box" class="form_box">
    <%= image_tag "exit_normal.png", id: "exit_button", 
                   draggable: "false" %>
    <p id="signup_title" class="form_title">Very Sign Up!</p>
    <div id="login_info" class="form_info">
      <%= form_for @account, remote: true, url: accounts_path, html: {id: "signup_form"} do |f| %>
        <div class="form_input_container">
          <%= f.label :username, id: "username_label", class: "form_label" %>
          <%= f.text_field :username, class: "form_input" %>
        </div>  
        <div class="form_input_container">
          <%= f.label :password, id: "password_label", class: "form_label" %>
          <%= f.password_field :password, class: "form_input" %>
        </div>
        <% if @account.errors.any? then %>
  	      <div class="error form_error"><%= sanitize @account.errors.full_messages[0] %></div>
        <% end %>
        <div id="color_picker_popup">
          <canvas width="64px" height="64px" id="open_color_picker_signup" class="hori-center"></canvas>
          <div id="color_picker_location"></div>
        </div>
        <%= f.hidden_field "color", value: session[:color] %>
        <div id="underline" class="underline"></div>
        <%= image_tag "doge_fooce_thumb.png", id: "signup_form_doge_img", class: "hori-center form_img" %>
        <div id="signup_submit_container" class="form_input_container">
          <%= f.submit "Sign Up", class: "form_submit hori-center", id: "signup_form_submit" %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="preload_signup_form" class="form_preload">
    <%= image_tag "exit_highlight.png", height: "1px", width: "1px" %>
    <%= image_tag "exit_pressed.png", height: "1px", width: "1px" %>
  </div>
  <%= javascript_include_tag "exit-button-bundle" %>
  <%= javascript_include_tag "signup-form-bundle" %>
  <script type="text/javascript">
    var signupForm = new makeSignupForm ();
    var exitButton = new makeExitButton ("exit_button", "signup_form_container",
                                         "<%= asset_path('exit_normal.png') %>",
                                         "<%= asset_path('exit_highlight.png') %>",
                                         "<%= asset_path('exit_pressed.png') %>");
    exitButton.bindClick (function () {
      $("#ls_form_container").css ("display", "none");
    });
    var signup_opener = new ColorOpener ("<%= session[:color] %>", "open_color_picker_signup",
                                         "color_picker_location",
  	  			                             "color-picker-container");
  </script>
</div>

app/views/accounts/color.html.erb
<%= render 'color_picker' %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password_Digest</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.username %></td>
        <td><%= account.password_digest %></td>
        <td><%= account.salt %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/login.html.erb
<%= render 'login_form' %>

app/views/accounts/new.html.erb
<%= render 'sign_up_form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<div style="position: relative; top: 71px;">
  <p>
    This will be fixed later :,(
  </p>
</div>
